### ISSUE TITLE
Wrong Description

### ISSUE THREAD

**Issue by screeny05** [saki007ster/language-swig#2]
Sorry but the Grammar in this package is for this [SWIG](http://www.swig.org/) not and not the templating-language

**Comment by kankaristo** [comment]
Yeah, this is kind of confusing.

I might not have installed this package if I hadn't seen this issue (I was actually looking for SWIG grammar support, instead of Swig grammar support).

**Comment by saki007ster** [comment]
The package is for [Swig](http://paularmstrong.github.io/swig/)

**Comment by kankaristo** [comment]
Really??!

[swig.cson](https://github.com/saki007ster/language-swig/blob/master/grammars/swig.cson) mentions C#, Java, Perl, Python, Ruby, etc. which all relate to SWIG, not Swig.

It says the grammar is based off of C++, which is true for SWIG, whereas Swig is based off of JavaScript.

It has `%{ %}` which is a SWIG code block, not a Swig one (`{% %}`).

The file types are `.i` and `.swg` which are for SWIG, but Swig uses `.html`.

All of the keywords seem to be for SWIG, not Swig.

Are you sure this package is for Swig? Because it seems to have terrible support for that and great support for SWIG.
